let productData = [
    {
        id:"google500",
        name:"Google card (HKD500)",
        price:500,
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia similique quos officiis dolorum fugit sit.",
        img:"../images/img-3.jpg",
    },
    {
        id:"google100",
        name:"Google card (HKD100)",
        price:100,
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia similique quos officiis dolorum fugit sit.",
        img:"../images/img-3.jpg",
    },
    {
        id:"google5000",
        name:"Google card (JPY5000)",
        price:300,
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia similique quos officiis dolorum fugit sit.",
        img:"../images/img-4.jpg",
    },
    {
        id:"google3000",
        name:"Google card (JPY3000)",
        price:200,
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia similique quos officiis dolorum fugit sit.",
        img:"../images/img-4.jpg",
    },
    {
        id:"itunes500",
        name:"iTunes card (HKD500)",
        price:500,
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia similique quos officiis dolorum fugit sit.",
        img:"../images/img-1.jpg",
    },
    {
        id:"itunes100",
        name:"iTunes card (HKD100)",
        price:100,
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia similique quos officiis dolorum fugit sit.",
        img:"../images/img-1.jpg",
    },
    {
        id:"itunes5000",
        name:"iTunes card (JPY5000)",
        price:300,
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia similique quos officiis dolorum fugit sit.",
        img:"../images/img-2.jpg",
    },
    {
        id:"itunes3000",
        name:"iTunes card (JPY3000)",
        price:200,
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia similique quos officiis dolorum fugit sit.",
        img:"../images/img-2.jpg",
    },
    {
        id:"Nintendo500",
        name:"Nintendo card (HKD500)",
        price:500,
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia similique quos officiis dolorum fugit sit.",
        img:"../images/img-7.jpg",
    },
    {
        id:"Nintendo100",
        name:"Nintendo card (HKD100)",
        price:100,
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia similique quos officiis dolorum fugit sit.",
        img:"../images/img-7.jpg",
    },
    {
        id:"Nintendo5000",
        name:"Nintendo card (JPY5000)",
        price:300,
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia similique quos officiis dolorum fugit sit.",
        img:"../images/img-8.jpg",
    },
    {
        id:"Nintendo3000",
        name:"Nintendo card (JPY3000)",
        price:200,
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia similique quos officiis dolorum fugit sit.",
        img:"../images/img-8.jpg",
    },
    {
        id:"Playstation500",
        name:"PS card (HKD500)",
        price:500,
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia similique quos officiis dolorum fugit sit.",
        img:"../images/img-5.jpg",
    },
    {
        id:"Playstation100",
        name:"PS card (HKD100)",
        price:100,
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia similique quos officiis dolorum fugit sit.",
        img:"../images/img-5.jpg",
    },
    {
        id:"Playstation5000",
        name:"PS card (JPY5000)",
        price:300,
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia similique quos officiis dolorum fugit sit.",
        img:"../images/img-6.jpg",
    },
    {
        id:"Playstation3000",
        name:"PS card (JPY3000)",
        price:200,
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia similique quos officiis dolorum fugit sit.",
        img:"../images/img-6.jpg",
    },
];